//
//  AIProvenanceView.swift
//  AI Camera Coach
//

import SwiftUI

struct AIProvenanceView: View {
    let provenance: AIProvenance

    var body: some View {
        HStack(spacing: 6) {
            Image(systemName: provenance.icon)
                .font(.caption2.weight(.semibold))
            Text(provenance.runsOnDevice ? "On-device · \(provenance.displayName)" : provenance.displayName)
                .font(.caption2.weight(.semibold))
        }
        .foregroundStyle(provenance.tint)
        .padding(.horizontal, 8)
        .padding(.vertical, 4)
        .background(provenance.tint.opacity(0.15), in: Capsule())
        .overlay(Capsule().stroke(provenance.tint.opacity(0.45), lineWidth: 0.5))
        .accessibilityLabel("Generated by \(provenance.displayName)")
    }
}
